apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    service: reverseproxy
spec:
  selector:
    matchLabels:
      service: reverseproxy
  replicas: 2
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - name: udagram-node
        image: algyjr/reverseproxy:v1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1200Mi"
            cpu: "500m"
          limits:
            memory: "1500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      restartPolicy: Always