name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the udagram-api-user Docker image
      run: docker build ./udagram-api-user --file ./udagram-api-user/Dockerfile --tag algyjr/udagram-api-user:v1
    - name: Build the udagram-api-feed Docker image
      run: docker build ./udagram-api-feed --file ./udagram-api-feed/Dockerfile --tag algyjr/udagram-api-feed:v1
    - name: Build the reverseproxy Docker image
      run: docker build ./udagram-reverseproxy --file ./udagram-reverseproxy/Dockerfile --tag algyjr/reverseproxy:v1
    - name: Build the udagram-frontend Docker image
      run: docker build ./udagram-frontend --file ./udagram-frontend/Dockerfile --tag algyjr/udagram-frontend:v2
    
    - name: Docker Push udagram-api-user
      run: docker push ${{secrets.DOCKER_USERNAME}}/udagram-api-user:v1
    - name: Docker Push udagram-api-feed
      run: docker push ${{secrets.DOCKER_USERNAME}}/udagram-api-feed:v1
    - name: Docker Push reverseproxy
      run: docker push ${{secrets.DOCKER_USERNAME}}/reverseproxy:v1
    - name: Docker Push udagram-frontend
      run: docker push ${{secrets.DOCKER_USERNAME}}/udagram-frontend:v2